name: hearvalidator wav2vec2

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
#        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: apt-get
      run: |
        sudo apt-get install -y libsndfile-dev
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install hearvalidator
    - name: Validate hearbaseline.wav2vec2
      run: |
        hear-validator hearbaseline.wav2vec2
